= RISC-V Profiles
Version 0.1-draft
:doctype: article
:encoding: utf-8
:lang: en
:toc: left
:numbered:
:stem: latexmath
:le: &#8804;
:ge: &#8805;
:ne: &#8800;
:approx: &#8776;
:inf: &#8734;

:sectnums!:

== Status

*This is only an initial proposal and is likely to change substantially before
being standardized.*

:sectnums:

== Introduction

RISC-V was designed to provide a highly modular and extensible
instruction set, and includes a large and growing set of standard and
custom extensions.  This flexibility can be used to highly optimize an
individual design by including only the exact set of ISA features
required for an application, but this flexibility also leads to a
combinatorial explosion in possible ISA choices.  Many application
areas depend on a rich software ecosystem, which is only made possible
by reducing the possible combinations of ISA features that the
software ecosystem has to support.  Architecture profiles are intended
to provide a structure for capturing the widely used combinations of
instruction set extensions, and are intended to be used by hardware
and software platform specifications to describe the ISA portions of
the platforms.

As RISC-V evolves over time, the set of ISA features supported by each
software ecosystem will also want to evolve over time, and new
software ecosystems will be added.  To help manage this evolution,
RISC-V is moving towards a model of regular annual delivery of a
coherent set of ISA updates according to an ISA roadmap, and
architecture profiles are intended to provide the natural structure
for planning, packaging, and releasing these ISA updates.

The architecture profiles will also be used for branding and to
advertise compatibility with the RISC-V standard.

This document describes the general structure of RISC-V architecture
profiles and also the specifics of the first three families of
architecture profiles: RVI20, RVM20, and RVA20.

== Profiles versus Platforms

A _software_ _platform_ is a common set of specifications for an
execution environment, in which software targeted for that platform
can run.

A _hardware_ _platform_ is a common set of specifications for hardware
systems (which can be viewed as physical realizations of an execution
environment).  Most hardware platforms have a defined boot mechanism,
which can configure and initialize an instance of a software platform
on the hardware platform.

Both software and hardware platforms include specifications for many
features beyond details of the ISA used by RISC-V processors in the
platform (e.g., behavior of environment calls in a software platform
or location of memory regions in a hardware platform).  Architecture
profiles factor out ISA-specific definitions from platform definitions
to allow profile specifications to be reused across different
platforms, and to be used by tools (e.g., compilers) that are common
across many different platforms.

== Components of a Profile

=== Profile Naming Convention

A profile name is a string comprised of:

. prefix RV for RISC-V
. a specific profile family string (I, M, or A initially)
. a numeric string giving the first complete calendar year for which
the profile is ratified, represented as number of years after year
2000 (i.e., 20 for profiles built on specifications ratified during 2019)
. an optional privilege mode (U, S, M), if the profile is differentiated by
privilege mode (privilege mode is required as separator if there's a following base specifier
starting with a number)
. an optional base specifier, if the profile supports different bases

A _profile_ _family_ is a set of profiles that are designed for the
same applications but vary in base ISA and privilege mode.

The initial profiles based on specifications ratified in 2019 are:

- RVI20 basic unprivileged instructions for RV32I
- RVI20U64 basic unprivileged instructions for RV64I
- RVM20, RVM20S32, RVM20U32 machine-mode profile for microcontrollers based on RV32I
- RVM20M64, RVM20S64, RVMU64  machine-mode profile for microcontrollers based on RV64I
- RVA20M, RVA20S, RVA20U, application-processor profiles for different privilege modes on RV64I
- RVA20M32, RVA20S32, RVA20U32, application-processor profiles for different privilege modes on RV32I

Note that a given profile family implies a default base (RV32I or
RV64I) based on the most common choice for that profile family (e.g.,
RV32I for RVM and RV64I for RVA).

=== Base and Extensions

An architecture profile has a mandatory base instruction set (RV32I or
RV64I).  In addition, the profile categorizes available ISA extensions
into four categories:

. Mandatory
. Supported
. Unsupported
. Incompatible

As the name implies, _Mandatory_ ISA extensions are a required part of
the profile.  Implementations of the profile must provide these, and
software using the profile can assume they exist.

_Supported_ extensions are those that are optional, but which
are expected to be fully supported by software platforms using this
profile.

_Unsupported_ extensions are those that are optional, but for
which it is not expected that software platforms will provide full, or
any, support.

Software platforms may provide a discovery mechanism to determine what
optional extensions are present.

_Incompatible_ extensions are those that conflict with the base or
optional extensions.  Software can assume these extensions are not
present.

All components of a ratified profile must themselves have been
ratified.

=== Execution Environments for a Profile

In general, the behavior of RISC-V instructions depends on the
execution environment in which they run.  To remain generic and usable
by different software platforms, profiles assume only bare execution
environments.

The initial set of profiles are defined for different bare execution
environments that are primarily distinguished by their most-privileged
supported mode.

For example, the RVI20 profile is defined for a bare unprivileged
execution environment.  The ECALL instruction in an RVI20 profile is
only required to cause a requested trap to the execution environment.
The details of how the requested trap is handled by the execution
environment are not specified by the profile.

As another example, the RVA20S profile is only defined for a
supervisor-mode execution environment.  An ECALL instruction while in
supervisor mode is only required to cause a requested trap to the
execution environment.  How that trap is handled by the execution
environment is not specified in the profile (normally, a software
platform using the RVA20S profile would describe the behavior of
specific ECALLs). In contrast, an ECALL instruction while in user mode
in the RVA20S profile will cause a contained trap to supervisor mode,
as specified by the privileged architecture.

== RVI20 Profiles

The RVI20 family of profiles are intended to represent the minimal
level of compatibility with the RISC-V specifications that can be
officially branded as RISC-V compatible.

The RVI20 profiles use an unprivileged execution environment and
unless otherwise specified use an RV32I base (i.e., RVI20 implies
RVI20U32).

=== RVI20 Base

The RVI20 profile includes all instructions in the unprivileged RV32I
base instruction set.

The RVWMO memory model is followed.

Misaligned loads and stores are not required to be supported and may
cause a fatal trap to the execution environment.

ECALL and EBREAK instructions cause requested traps to the execution
environment.

=== RVI20 Mandatory Extensions

- Zifencei

=== RVI20 Supported Extensions

- M
- A
- F
- D
- C

Note Zicsr is only required if F is supported.

=== RVI20 Unsupported Extensions

- Q

There is no significant demand for hardware or software support for Q.

=== RVI20 Incompatible Extensions

None.

=== RVI20U64 Variant

Same as above except base is RV64I.

== RVM20 Profiles

The RVM20 family of profiles are intended to be used in
microcontroller applications, and the default base is RV32I.

=== RVM20U Profile

The RVM20U profile represents the behavior of unprivileged code in
microcontrollers.

RVM20U is identical to RVI20, except that WFI is a supported extension.

=== RVM20S Profile

This profile provides a supervisor-mode execution environment.

The base is RV32I and supervisor and user mode are supported.

Only the Sbare setting of satp is mandatory, and may be hardwired to
zero.  (Software should require all 0s written to satp to set Sbare).

==== RVM20S Mandatory Extensions

- Zifencei

==== RVM20S Supported Extensions

- M
- A
- F
- D
- C
- stvec writeable, direct+vectored modes, ...
- scounteren
- stval set on illegal instruction

==== RVM20S Unsupported extensions

- Sv32

=== RVM20M Profile

This profile provides a machine-mode execution environment.

The base is RV32I and machine-mode is supported.

==== RVM20M Mandatory Extensions

- Zifencei

==== RVM20M Supported Extensions

- M
- A
- F
- D
- C
- misa non zero
- mvendorid non zero
- marchid non zero
- mimpid non zero
- mtvec writable, direct+vectored modes, ...
- medeleg/mideleg (individual delegatable bits?)
- hardware perf monitors
- mcountinhibit
- mtval set on illegal instruction
- User mode (adds MPP bits, MPRV,,
- Supervisor mode (Sbare only)
- PMPs
- TW (timeout wait - or make mandatory?)
- TSR (Trap SRET - or make unsupported?)

==== RVM20M Unsupported extensions

- Sv32 (including SUM)
- TVM






== RVA20 Profiles

The RVA20 family of profiles are intended to be used as
application processors, and the default base is RV64I.


=== RVA20U64 Profile

The RVA20U64 profile represents the behavior of unprivileged code in
applications processors.

RVA20U64 profile is identical to RVI20U64 except that misaligned
memory accesses must be supported.

=== RVA20S64 Profile


=== RVA20M64 Profile

