== Components of a Profile

=== Profile Family

Every profile is a member of a _profile_ _family_.  A profile family
is a set of profiles that share the same base ISA but which vary in
highest-supported privilege mode.  The initial two types of family
are:

- generic unprivileged instructions (I)
- application processors running rich operating systems (A)

NOTE: More profile families may be added over time.

A profile family may be updated no more than annually, and the release
calendar year is treated as part of the profile family name.

Each profile family is described in more detail below.

=== Profile Privilege Mode

RISC-V has a layered architecture supporting multiple privilege modes,
and most RISC-V platforms support more than one privilege mode.
Software is usually written assuming a particular privilege mode
during execution.  For example, application code is written assuming
it will be run in user mode, and kernel code is written assuming it
will be run in supervisor mode.

NOTE: Software can be run in a mode different than the one for which
it was written. For example, privileged code using privileged ISA
features can be run in a user-mode execution environment, but will
then cause traps into the enclosing execution environment when
privileged instructions are executed.  This behavior might be
exploited, for example, to emulate a privileged execution environment
using a user-mode execution environment.

The profile for a privilege mode describes the ISA features for an
execution environment that has the eponymous privilege mode as the
most-privileged mode available, but also includes all supported
lower-privilege modes.  In general, available instructions vary by
privilege mode, and the behavior of RISC-V instructions can depend on
the current privilege mode.  For example, an S-mode profile includes
U-mode as well as S-mode and describes the behavior of instructions
when running in different modes in an S-mode execution environment,
such as how an `ecall` instruction in U-mode causes a contained trap
into an S-mode handler whereas an `ecall` in S-mode causes a requested
trap out to the execution environment.

A profile may specify that certain conditions will cause a requested
trap (such as an `ecall` made in the highest-supported privilege mode)
or fatal trap to the enclosing execution environment.  The profile
does not specify the behavior of the enclosing execution environment
in handling requested or fatal traps.

NOTE: In particular, a profile does not specify the set of ECALLs
available in the outer execution environment.  This should be
documented in the appropriate binary interface to the outer execution
environment (e.g., Linux user ABI, or RISC-V SEE).

NOTE: In general, a profile can be implemented by an execution
environment using any hardware or software technique that provides
compatible functionality, including pure software emulation.

A profile does not specify any invisible traps.

NOTE: In particular, a profile does not constrain how invisible traps
to a more-privileged mode can be used to emulate profile features.

A more-privileged profile can always support running software to
implement a less-privileged profile from the same profile family.  For
example, a platform supporting the S-mode profile can run a
supervisor-mode operating system that provides user-mode execution
environments supporting the U-mode profile.

NOTE: Instructions in a U-mode profile, which are all executed in user
mode, have potentially different behaviors than instructions executed
in user mode in an S-mode profile.  For this reason, a U-mode profile
cannot be considered a subset of an S-mode profile.

=== Profile ISA Features

An architecture profile has a mandatory ratified base instruction set
(RV32I or RV64I for the current profiles).  The profile also includes
ratified ISA extensions placed into two categories:

. Mandatory
. Optional

As the name implies, _Mandatory_ _ISA_ _extensions_ are a required
part of the profile.  Implementations of the profile must provide
these.  The combination of the profile base ISA plus the mandatory ISA
extensions are termed the profile _mandates_, and software using the
profile can assume these always exist.

The _Optional_ category (also known as _options_) contains extensions
that may be added as options, and which are expected to be generally
supported as options by the software ecosystem for this profile.

NOTE: The level of "support" for an Optional extension will likely
vary greatly among different software components supporting a profile.
Users would expect that software claiming compatibility with a profile
would make use of any available supported options, but as a bare
minimum software should not report errors or warnings when supported
options are present in a system.

An optional extension may comprise many individually named and
ratified extensions but a profile option requires all constituent
extensions are present.  In particular, unless explicitly listed as a
profile option, individual extensions are not by themselves a profile
option even when required as part of a profile option.  For example,
the Zbkb extension is not by itself a profile option even though it is a
required component of the Zkn option.

NOTE: Profile optional extensions are intended to capture the
granularity at which the broad software ecosystem is expected to cope
with combinations of extensions.

All components of a ratified profile must themselves have been
ratified.

Platforms may provide a discovery mechanism to determine what optional
extensions are present.

Extensions that are not explicitly listed in the mandatory or optional
categories are termed _non-profile_ extensions, and are not considered
parts of the profile.  Some non-profile extensions can be added to an
implementation without conflicting with the mandatory or optional
components of a profile.  In this case, the implementation is still
compatible with the profile even though additional non-profile
extensions are present.  Other non-profile extensions added to an
implementation might alter or conflict with the behavior of the
mandatory or optional extensions in a profile, in which case the
implementation would not be compatible with the profile.

NOTE: Extensions that are released after a given profile is released
are by definition non-profile extensions.  For example, mandatory or
optional profile extensions for a new profile might be prototyped as
non-profile extensions on an earlier profile.

=== Profile Naming Convention

A profile name is a string comprised of, in order:

. Prefix *RV* for RISC-V.
. A specific profile family name string.  Initially a single letter (*I*, *M*, or *A*), but later profiles may have longer family name strings.
. A numeric string giving the first complete calendar year for which
the profile is ratified, represented as number of years after year
2000, i.e., *20* for profiles built on specifications ratified during 2019. The year string will be longer than two digits in the next century.
. A privilege mode (*U*, *S*, *M*).  Hypervisor support is treated as an option.
. A base ISA XLEN specifier (*32*, *64*).

The initial profiles based on specifications ratified in 2019 are:

- RVI20U32 basic unprivileged instructions for RV32I
- RVI20U64 basic unprivileged instructions for RV64I
- RVA20U64, RVA20S64 64-bit application-processor profiles

NOTE: Profile names are embeddable into RISC-V ISA naming strings.
This implies that there will be no standard ISA extension with a name
that matches the profile naming convention.  This allows tools that
process the RISC-V ISA naming string to parse and/or process a combined
string.
