== RVB23.1 Profiles Release

This document specifies the RVB23.1 Profile Family. RVB23.1 is 
the first minor release intended to expand upon
the RVB23 major release of the RVB23 Family of RISC-V Application 
Processor Profile.

include::rvb-profile-overview-body.adoc[]

=== RVB23.1 Profiles

This is a minor release of the RVB23 Profile Family. As such, Minor Profiles
do not contain any new mandatory extensions and are expected to be
built on top of the extensions listed in the RVB23 profiles. For
the sake of simplicity when referring to this profile in code or
use in a command line argument, all instances of the period will
be replaced with the lower case letter 'p', as in `rvb23p1s64`

Only supervisor-mode (`rvb23p1s64`) profiles are
specified in this family.

==== `rvb23p1s64` Profile

The `rvb23p1s64` profile specifies the ISA features available to a
supervisor-mode execution environment in 64-bit applications
processors.  `rvb23p1s64` is based on and requires an rvb23s64
implementation.

===== `rvb23p1s64` Optional Extensions

`rvb23p1s64` has the same unprivileged options as `rvb23u64`,

The privileged options in `rvb23p1s64` are listed in the following
sections and are additional options to the `rvb23s64` Profile.

====== Localized Options

There are no privileged localized options in `rvb23p1s64`.

====== Development Options

The following are new privileged development options in `rvb23p1s64`:

- *Svrsw60t59b* PTE reserved-for-software bits.

NOTE: *Svrsw60t59b* is used to avoid optionality in Linux kernel page tables 

- *Ssdbltrap* Double Trap, which is included to make trap handling more robust

====== Expansion Options

The following are new privileged expansion options in `rvb23p1s64`:

- *Sscfg* Supervisor Counter Delegation.

- *Ssctr* Control Transfer Records, CTR.

NOTE: *Ssctr* also implies inclusion of *Sscsrind* (indirect CSR access)

- *Ssqosid* QoS identifiers.

====== Transitory Options

There are no privileged transitory options in `rvb23p1s64`.

=== Glossary of ISA Extensions

The following extensions have not yet been incorporated into the RISC-V
Instruction Set Manual; the hyperlinks lead to their separate specifications.

- https://riscv.atlassian.net/browse/RVS-3647[Svrsw60t59b]
- https://riscv.atlassian.net/browse/RVS-1005[Sscfg]
- https://riscv.atlassian.net/browse/RVS-973[Ssctr]

The following privileged ISA extensions are defined in Volume II
of the https://github.com/riscv/riscv-isa-manual[RISC-V Instruction Set Manual].

- https://docs.riscv.org/reference/isa/priv/ssdbltrp.html[Ssdbltrap]
- https://docs.riscv.org/reference/isa/priv/supervisor.html#ssqosid[Ssqosid]
- https://docs.riscv.org/reference/isa/priv/indirect-csr.html[Sscsrind]
